version: '3.8'

services:
  # Serviço de Backend com Laravel + PHP-FPM
  app:
    build:
      context: ./backend
    container_name: laravel_app
    volumes:
      - ./backend:/var/www
    depends_on:
      - mysql
    networks:
      - app-network

  # Serviço do Nginx
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  # Serviço do MySQL
  mysql:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: application
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  # Serviço do Frontend com Vue.js
  frontend:
    build:
      context: ./frontend
    container_name: vue_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    working_dir: /app
    environment:
      - HOST=0.0.0.0
    command: npm run dev
    depends_on:
      - app
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge